### PR TITLE
add ssh-tunnel command using aws emr socks command

### PR DESCRIPTION
**Pull request by timchan-lumoslabs**

### CODE REVIEW

**Comment by slpsys** [comment]
@timchan-lumoslabs 👍 this is awesome, but as someone who hasn't accessed the spark web UI via tunnel even manually, mind throwing in a sentence or two about how to navigate to the UI?

**Comment by timchan-lumoslabs** [comment]
In the AWS EMR console, there are instructions on how to set up foxyproxy.

screenshot

Once that is setup and the ssh-tunnel established, just point your browser that you configured foxyproxy with, to the following: 

http://<master-node>:8088

for example,

http://ec2-54-204-150-54.compute-1.amazonaws.com:8088

This is the hadoop namenode web console. 

If you have spark-shell running, you should see something like the following:

screenshot

Just click on the link to `ApplicationMaster` to access the Spark shell application UI.

**Comment by slpsys** [comment]
haha, sorry. 💯 what i meant, but i meant: can you put that in the `README.md`?

**Comment by timchan-lumoslabs** [comment]
whoops. my bad. 😄

**Comment by slpsys** [comment]
🍻

**Pull request merged**
